apiVersion: v1
kind: Namespace
metadata:
  name: scooby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatinfra
  namespace: scooby
spec:
  selector:
    matchLabels:
      app: tomcatinfra
  replicas: 2
  template:
    metadata:
      namespace: scooby
      name: tomcatinfra
      labels:
        app: tomcatinfra
    spec:
      containers:
      - image: saravak/tomcat8
        name: tomcatapp
